### ISSUE TITLE
GET query parameters

### ISSUE THREAD

**Issue by leolanzinger** [3osman/live-api#5]
What should I pass as "platforms"?
And "numpage"?

**Comment by 3osman** [comment]
platforms comma separated param, available now are youtube and periscope
so:  platform=youtube,periscope or one of them

numpage I am still working to figure out the paging, but basically it is for paging, if we have 16 results and you display 9 per page, then you have page 1 and 2, i was thinking of fetching from the server per page instead of fetching all and handling paging client side.

**Comment by leolanzinger** [comment]
great thanks 👍🏼
